# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be90e98606a5a236f590f1255403f6aaa160bb8c2882516f2c1bd35c528849fce54ffc70d3ffc6ad52e6baff59eef9306ca1e43bb266f5072a7177fecc2e60fb

test:
  secret_key_base: 9dc2003ed1fe2ba82c80d04bc023bc3470396419e01e00d88c618fdfb3bdd93c407e4e24d6e1456c0df5c42627a58700c4d63f08c3d2c7c0a93466116a35d75d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
